apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  FLASK_DB_USER: cG9zdGdyZXM=    # Base64 de "postgres"
  FLASK_DB_PASSWORD: c2VjcmV0cGFzcw==    # Base64 de "secretpass"
  POSTGRES_USER: cG9zdGdyZXM=    # Base64 de "postgres"
  POSTGRES_PASSWORD: c2VjcmV0cGFzcw==    # Base64 de "secretpass"
